# Generated by Django 4.0 on 2022-06-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_fila_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feijao', models.CharField(choices=[('Caldo', 'Caldo'), ('Tropeiro', 'Tropeiro'), ('Feijoada', 'Feijoada')], max_length=20)),
                ('proteina', models.CharField(choices=[('Carne de Boi Cozida', 'Carne de Boi Cozida'), ('Ovo Cozido', 'Ovo Cozido'), ('Frango Assado', 'Frango Assado'), ('Estrogonofe', 'Estrogonofe'), ('Lasanha', 'Lasanha')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='fila',
            name='cardapio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cardapio'),
            preserve_default=False,
        ),
    ]
